mode: deployment

image:
  repository: "otel/opentelemetry-collector-contrib"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024

    # --- CORREÇÃO: Simplificando o nome para 'resource' ---
    resource:
      attributes:
        - key: deployment.environment
          value: "sre-lab"
          action: upsert
        - key: k8s.cluster.name
          value: "carpenter-k3s-local"
          action: upsert
        - key: data.origin
          value: "otel-collector-gateway"
          action: upsert
    # ------------------------------------------------------

  exporters:
    otlp:
      endpoint: "tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true
    debug:
      verbosity: detailed

  service:
    pipelines:
      traces:
        receivers: [otlp]
        # A ordem é vital: Enriqueça (resource) -> Depois processe em lote (batch)
        processors: [resource, batch] 
        exporters: [otlp, debug]
      metrics: null
      logs: null