{
 "title": "Teste - 1",
 "description": "primeiro teste",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name, http_method) (rate(traces_span_metrics_calls_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(traces_span_metrics_duration_milliseconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (service_name, http_status_code) (rate(traces_span_metrics_calls_total{http_status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "{{http_status_code}} - {{service_name}}"
    }
   ]
  }
 ]
}